var data = [{
    id: "VA",
    state: "Virginia",
    UW: "CTIC",
    jacket:"Refinance Rate – Standard Loan -> REFINANCE LOAN – ALTA Short Form Residential Loan Policy 12/03/12 w-VA Mod_434 – Refinance Loan Policy",
    split: 13,
    end: false,
    cpl: "$30",
    pud: "5.1",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s Aff','Deed of Trust', 'Executed Settlement Statement']
  },
  {
    id: "MD",
    state: "Maryland",
    UW: "FATIC",
    jacket: "ALTA Short Form Residential Loan Policy (Rev. 6-16-07) (A&B)",
    split: 13,
    end: false,
    cpl: "$45",
    pud: "5.1/4.1",
    signer: "William G. Reilly",
    review: ['NFT ABA',  'Owner\'s aff']
  },
  {
    id: "CO",
    state: "Colorado",
    UW:"CTIC",
    split: 15,
    jacket:",",
    end: { 8.1: 50, 6: 30, 9: '', 4.1: '', 5.1: '' },
    cpl: "$25",
	pud: "5.1/4.1",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s Aff',"Gap Aff", 'Marital Status Aff']
  },
  {
    id: "AL",
    state: "Alabama",
    UW: "",
    split: 0,
    jacket:"",
    split: 20,
    end: false,
    cpl: "$25/ $25 (BWR opt.)",
    pud: "5.0 or 5.1",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', 'Fire Dues Aff']
  }, 
  {
    id: "DC",
    state: "District of Columbia",
    UW: "FATICO",
    split: 13,
    jacket:"ALTA Short Form Residential Loan Policy (6-17-06; Rev. 4-8-16) (A&B)",
    end: false,
    cpl: "$50",
    pud: "?",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s Aff', 'Gap Aff', 'Executed Settlement Statement', 'Deed of Trust']
  },  
  {
    id: "FL",
    state: "Florida",
    UW: "CW",
    split: 30,
    jacket:"?",
    end: {"9":"10% prem"},
    cpl: "n/a",
    pud: "5.1/4.1",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', 'Borrower Affidavit (BA)', 'Gap Affidavit & Indemnity (GA)', 'Marital Status (MSA)', '•	Title Affidavit (TA)', 'Indemnity Agreement (IA) [not notarized]','Lien Affidavit (LA)', 'Homestead Affidavit (HA)', 'FL Premium Disclosure (FPD) [not notarized]', 'Compliance Agreement (CA)' ]
  },  
  {
    id: "GA",
    state: "Georgia",
    UW: "FATICO",
    split: 15,
    jacket:"ALTA Short Form Residential Loan Policy (Rev. 6-16-07) (A&B)",
    end: true,
    cpl: "$50",
    pud: "5.0",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', 'Security Deed', "Executed Settlement Statement"]
  },  
  {
    id: "IL",
    state: "Illinois ",
    UW: "FATICO",
    split: 15,
    jacket:"ALTA Short Form Residential Loan Policy (Rev. 6-16-07) (A&B)",
    end: false,
    cpl: "Lender $25; Borrower $25 for sale/$50 for refi; Seller $50",
    pud: "5.1/4.1",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', "Marital Status Aff (notarized)", "Personal Undertaking", 'Deed of Trust', "Executed Settlement Statement"]
  },  
  {
    id: "IN",
    state: "Indiana",
    UW: "CTIC",
    split: 15,
    jacket:"BASIC LOAN – ALTA Short Form Residential Loan Policy 12/03/12_434 – Basic Loan Rates",
    end: false,
    cpl: "15",
    pud: "5.0/4.0",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', 'ABA (x2 NFTS/NFCU & NFTS/CTS)', "Gap Aff (notarized) ",	"Mortgagor’s Aff (notarized)","Borrower’s Aff (notarized)", "Homeowner’s Aff (notarized)","Tax Benefits Sheet"]
  },  
  {
    id: "KS",
    state: "Kansas ",
    UW: "CTIC",
    split: 15,
    jacket:"REFINANCE LOAN – ALTA Short form Residential Loan Policy 12/03/12 w-KS/MO mod_434 – Refinance Rates",
    end: "filed rate",
    cpl: "n/a",
    pud: "5.0- first lien",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', 'Gap (notarized)', "Marital Status Affidavit (notarized)","Executed Settlement statement", "Deed of trust"]
  },   
  {
    id: "KY",
    state: "Kentucky",
    UW: "CTIC",
    split: 15,
    jacket:"REFINANCE LOAN – ALTA Short Form Residential Loan Policy 12/03/12 w-KY Mod_434 – REFINANCE RATE",
    end: "$30/",
    cpl: "$50 lender; $25/borrower (optional) (+ lender's premium tax [dependant on county], full amount remitted)",
    pud: "5.0/4.0",
    signer: "Mel",
    review: ['NFT ABA', 'Owner\'s aff',"Owners Aff (notarized)","ABA (x2 NFTS/NFCU & NFTS/CTS)","Gap", "Marital Status Affidavit (notarized)",
    "Cert in Residential Transactions",
    "Aff and Indemnity (notarized)",
     'Executed Settlement Statement', "Deed of trust"]
  },    
  {
    id: "LA",
    state: "Louisiana",
    UW: "CTIC",
    split: 20,
    jacket:"BASIC LOAN - ALTA Short Form Residential Loan Policy 06/16/07 for LA 04/01/14_452 - Loan Rate",
    end: "varies per endorsement (commonly used $50 -100); CPL paid directly to UW by attorney",
    cpl: "$25",
    pud: "5.0",
    signer: "Melanie Johnson",
    review: ['NFT ABA', 'Owner\'s aff', 'Executed Settlement Statement', "Deed of trust"]
  },     
  {
    id: "ME",
    state: "Maine",
    UW: "CTIC",
    split: 20,
    jacket:"REFINACE LOAN – ALTA Short Form Residential Loan Policy 12/03/12 w-ME Mod_434 – Refinance Rates",
    end: " 9.3- Residential Endorsement Flat Fee: $75.00 (plus $50 survey aff, subject to split [$40.00 to NFTS, $10.00 to CTIC])",
    cpl: "$25",
    pud: "",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff',"Gap (notarized)",
    "Survey Aff (notarized)",
    'Residential Mortgage Survey Aff (notarized)',
    'No Open Lien Aff (notarized)',
     'Executed Settlement Statement', "Deed of trust"]
  },     
  {
    id: "MA",
    state: "Massachusetts ",
    UW: "CTIC",
    split: 25,
    jacket:"BASIC LOAN – ALTA Short Form Residential Loan Policy 06/16/07-342 – Standard Loan Policy",
    end: false,
    cpl: "n/a",
    pud: "5.0",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', 'Executed Settlement Statement', "Deed of trust", "FTO STATE"]
  },     
  {
    id: "MI",
    state: "Michigan ",
    UW: "CTIC",
    split: 15,
    jacket:"BASIC LOAN – ALTA Short Form Residential Loan Policy 12/03/12_434 – Basic Loan Rates",
    end: false,
    cpl: "n/a",
    pud: "5.1/4.1",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', "Gap (notarized)"," Marital Status Aff (notarized)","Personal Undertaking (notarized)", 'Executed Settlement Statement', "Deed of trust" ]
  },     
  {
    id: "MN",
    state: "Minnesota ",
    UW: "CTIC",
    split: 20,
    jacket:"REFINANCE LOAN - ALTA Short Form Residential Loan Policy 12/03/12_434 - Refinance Loan Rate",
    end: "some endorsements 10%; some flat $50-200; some at no charge",
    cpl: "n/a",
    pud: "5.0/4.0",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff',"Gap (notarized)", "Marital Status Affidavit (notarized)", "Aff Regarding Seller (notarized)",  'Executed Settlement Statement', "Deed of trust"]
  },     
  {
    id: "MS",
    state: "Mississippi ",
    UW: "CTIC",
    split: 20,
    jacket:"Mortgage Original Rate OR Reissue Loan Rate (as applicable)  BASIC LOAN – ALTA Short Form Residential Loan Policy 12/03/12_434 – Mortgage Original Rate OR REISSUE LOAN - ALTA Short Form Residential Loan Policy 12/03/12_434 – Reissue Loan Rate",
    end: "No charge on residential endorsements except ALTA 7 is $100",
    cpl: "$50",
    pud: "5.1/4.1",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff'," Gap (notarized)", "Marital Status Affidavit", "Indemnity and Hold Harmless Aff (notarized)", 'Executed Settlement Statement', "Deed of trust"]
  },     
  {
    id: "MO",
    state: "Missouri ",
    UW: "FATICO",
    split: 50,
    jacket:"First American – must be a licensed agent in the state for refi and purchase",
    end: "Missouri does not presently charge for any endorsements All filed endorsements except for the following are issued for a work fee only  No premium or risk rate applies*",
    cpl: "%25",
    pud: "5.1/4.1",
    signer: "Melanie Johnson",
    review: ['NFT ABA', 'Owner\'s aff', "Owner Affidavit (state specific)", " Gap", "Notice of Closing or Settlement Risk, Form T-3 (only if no policy issued)", "Title Insurance & Service Charge Disclosure", 
    "NFT ABA + MO AfB",
    "Marital Status", "CTS added: City Nuisance Fee Disclosure & Hold Harmless", 'Executed Settlement Statement', "Deed of trust"]
  },     
  {
    id: "NC",
    state: "North Carolina",
    UW: "FATICO",
    split: 15,
    jacket:"ALTA Short Form Residential Loan Policy (Rev. 6-16-07) (A&B)",
    end: "$21 each for 8.1, 9 and PUD—no charge for all others *Closing services insurance premium is an additional fee added to the base premium (refer to First American rate calculator) *Commitment Premium is $15",
    cpl: "n/a",
    pud: "5.0",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', 'Executed Settlement Statement', "Deed of trust"]
  },     
  {
    id: "NE",
    state: "Nebraska",
    UW: "CTIC",
    split: 15,
    jacket:"REFINANCE LOAN – ALTA Short Form Residential Loan Policy 12/03/12 w-NE Mod_434 – Refinance Rate",
    end: "$25 Each",
    cpl: "$25",
    pud: "",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', 'Executed Settlement Statement', "Deed of trust"]
  },        
  {
    id: "NH",
    state: "New Hampshire",
    UW: "CTIC",
    split: 20,
    jacket:"BASIC LOAN – ALTA Short Form Residential Loan Policy-Current Violations 04/02/15_492 – Original Mortgage Rate",
    end: "Flat package rate for survey and all endorsements\n Standard loan $125\nExpanded $175\n",
    cpl: "$25",
    pud: "5.1/4.1",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', "Owners Aff", "ABA (x2 NFTS/NFCU & NFTS/CTS)", "Gap Aff (notarized)", "Gap Indemnity (notarized)", "Marital Status Aff"," Policy Aff (/expanded coverage policy aff) (notarized)","Survey Aff (notarized)", 'Executed Settlement Statement', "Deed of trust"]
  },        
  {
    id: "NJ",
    state: "New Jersey"
    UW: "CTIC",
    split: 13,
    jacket:"REFINANCE LOAN - ALTA Short Form Residential Loan Policy-Current Violations 04/02/15 w-NJRB Mod 07/01/2018_506 – Refinance Loan Rates",
    end: "$25 each unless Enhanced policy is purchased *If Enhanced Lender’s policy is purchased then there are NO charges for endorsements however simultaneous issue fee is still applicable",
    cpl: "$75",
    pud: "5.1/4.1",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff',"Gap (notarized)", "Marital Status Aff (notarized)", "Aff of Title (notarized)", "Executed Settlement Statement"," Deed of trust"]
  },        
  {
    id: "OH",
    state: "Ohio",
    UW: "FATICO",
    split: 10,
    jacket:"ALTA Short Form Residential Loan Policy (Rev. 6-16-07) (A&B)",
    end: "varies up to $150 (reference RC)",
    cpl: "$40 lender; $20 borrower (optional)",
    pud: "5.0/4.0",
    signer: "Melanie Johnson",
    review: ['NFT ABA', 'Owner\'s aff'," Marital Status Aff (notarized)", "Closing Disclosure", "Notice of Availability and Offer of Closing Protection Coverage/Offer of CPL", "Affidavit of No New Improvements (notarized)", 'Executed Settlement Statement', "Deed of trust"]
  },        
  {
    id: "PA",
    state: "Pennsylvania ",
    UW: "CW",
    split: 0,
    jacket:"NA",
    end: false,
    cpl: "NA",
    pud: "NA",
    signer: "?",
    review: ['NFT ABA', 'Owner\'s aff',"Witness not required on Deed", " POA Alive & Well Affidavit does not need to record", " Outsale Affidavit is not required for Purchase Money MTG",  " Survey Waiver is not required per UW",  " NOP Judgments are listed in owner affidavit", 'Executed Settlement Statement', "Deed of trust"]
  },        
  {
    id: "RI",
    state: "Rhode Island",
    UW: "CTIC",
    split: 20,
    jacket:"REFINANCE LOAN - ALTA Short Form Residential Loan Policy 06/16/07_343 – Reduced Rates – Refinance Mortgages",
    end: "Endorsements 6.0, 6.1, and Alta 9 $25; Survey Deletion $25.00 (100% of endorsement fees go to UW)",
    cpl: "$35",
    pud: "4.0",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', "Tax cert (municipal lien cert)", 'Executed Settlement Statement', "Deed of trust"]
  },        
  {
    id: "SC",
    state: "South Carolina",
    UW: "CTIC",
    split: 40,
    jacket:"ALTA Short Form Residential Loan Policy 12/03/12 w/SC NS Mod_434",
    end: false,
    cpl: "$35",
    pud: "5.0",
    signer: "William G. Reilly",
    review: ['NFT ABA', 'Owner\'s aff', 'Executed Settlement Statement', "Deed of trust", "FTO state"]
  },        
  {
    id: "TN",
    state: "Tennessee ",
    UW: "CW",
    split: 15,
    jacket:"[select agent CLTIC] Loan Original Rates  BASIC LOAN – ALTA Short Form Residential Loan Policy 12/03/12 for TN_434 – Loan Original Rates",
    end: false,
    cpl: "$50",
    pud: "5.0",
    signer: "MEL",
    review: ["RISK RATE", 'NFT ABA', 'Owner\'s aff', "Gap ","Marital Status Affidavit", 'Executed Settlement Statement', "Deed of trust"]
  },        
  {
    id: "WV",
    state: "West Virginia ",
    UW: "CW",
    split: 15,
    jacket:"BASIC LOAN – ALTA Short Form Residential Loan Policy 12/03/12 w-WV Mod_434 – Loan Policy Rate OR REISSUE LOAN – ALTA Short Form Residential Loan Policy 12/03/12 w-WV Mod_434 – Reissue Loan Rate",
    end: "8.1 is $15 and included in split; $50 commitment included and subject to split (included in premium for split)",
    cpl: "$50",
    pud: "5.1/ 9.3",
    signer: "William G. Reilly",
    review: ['Owner\'s aff', 'Executed Settlement Statement', "Deed of trust"]
  },        
  {
    id: "WI",
    state: "Wisconsin",
    UW: "CTIC",
    split: 15,
    jacket:"REFINANCE LOAN – ALTA Short Form Residential Loan Policy 12/03/12 w-WI Mod_434 – Original Policy Rates - 2013",
    end: "Alta 6 and Alta 7 are $125, no charge for all others",
    cpl: "na",
    pud: "5.0",
    signer: "Mel",
    review: ['NFT ABA', 'Owner\'s aff', "Gap", "Marital Status Affidavit", "Owner’s Affidavit as to Liens and Possession", 'Executed Settlement Statement', "Deed of trust"]
  }
  

];
